name: ipsec-tunnel-create_c84f130f-eb38-4638-a2f6-f4dafd5e3355
label: configure ipsec tunnel with ike gateway and tunnel interface
description: |
  This skillet will take input variables and configure an IPSec Tunnnel, IKE Gateway
  and tunnel interface. IPv4 only

type: panos

labels:
  collection:
    - IPSEC
    - Configure

variables:
  - name: tunnel_name
    description: name of ipsec tunnel
    default: ipsec_tunnel_name
    type_hint: text
  - name: tunnel_interface
    description: Tunnel Interface tunnel.Number
    default: tunnel.1
    type_hint: text
  - name: tunnel_interface_zone
    description: Zone applied to the Tunnel Interface (must already exist on the firewall)
    default: untrust
    type_hint: text
  - name: preshared_key
    description: Preshared Key
    default: myPresharedKey
    type_hint: text
  - name: ike_gateway_name
    description: Name for the IKE Gateway
    default: ike-gateway
    type_hint: text
  - name: ike_version
    description: IKE Version
    default: ike_v2_preferred
    type_hint: dropdown
    dd_list:
      - key: ike_v2_only
        value: ikev2
      - key: ike_v2_preferred
        value: ikev2-preferred
  - name: local_interface_address
    description: IKE IP address/CIDR of the Local Interface
    default: 192.0.2.1/24
    type_hint: text
  - name: local_interface
    description: IKE Local Negotiating Interface Name
    default: ethernet1/1
    type_hint: text
  - name: peer_address
    description: IKE Peer Address
    default: 192.0.2.2
    type_hint: text
  - name: tunnel_route_name
    description: Name for the Static Tunnel Route Entry
    default: Tunnel_Route
    type_hint: text
  - name: remote_network_tunnel_route
    description: The Destination Network/CIDR routed into the tunnel interface
    default: 10.0.0.0/8
    type_hint: text
  - name: virtual_router_name
    description: Name of the virtual router (must already exist)
    default: default
    type_hint: text
  - name: vsys
    description: Vsys Name
    default: vsys1
    type_hint: text

snippets:
  - name: tunnel-interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface/tunnel/units
    element: |-
      <entry name="{{ tunnel_interface }}"/>

  - name: tunnel-zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys
    element: |-
      <entry name="{{ vsys }}">
        <zone>
          <entry name="{{ tunnel_interface_zone }}">
            <network>
              <layer3>
                  <member>{{ tunnel_interface }}</member>
              </layer3>
            </network>
          </entry>
        </zone>
      </entry>

  - name: import.xml
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys
    element: |-
      <entry name="{{ vsys }}">
        <import>
          <network>
            <interface>
              <member>{{ tunnel_interface }}</member>
            </interface>
          </network>
        </import>
      </entry>

  - name: virtual-router
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: virtual-router.xml
    element: |-
      <entry name="{{ virtual_router_name }}">
        <interface>
          <member>{{ tunnel_interface }}</member>
        </interface>
        <routing-table>
          <ip>
            <static-route>
              <entry name="{{ tunnel_route_name }}">
                <path-monitor>
                  <enable>no</enable>
                  <failure-condition>any</failure-condition>
                  <hold-time>2</hold-time>
                </path-monitor>
                <bfd>
                  <profile>None</profile>
                </bfd>
                <interface>{{ tunnel_interface }}</interface>
                <metric>10</metric>
                <destination>{{ remote_network_tunnel_route }}</destination>
                <route-table>
                  <unicast/>
                </route-table>
              </entry>
            </static-route>
          </ip>
        </routing-table>
      </entry>

  - name: ike-gateway
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/ike/gateway
    element: |-
      <entry name="{{ ike_gateway_name }}">
          <authentication>
              <pre-shared-key>
                  <key>{{ preshared_key }}</key>
              </pre-shared-key>
          </authentication>
          <protocol>
              <ikev2>
                  <dpd>
                      <enable>yes</enable>
                  </dpd>
              </ikev2>
              <version>{{ ike_version }}</version>
          </protocol>
          <local-address>
              <ip>{{ local_interface_address }}</ip>
              <interface>{{ local_interface }}</interface>
          </local-address>
          <protocol-common>
              <nat-traversal>
                  <enable>no</enable>
              </nat-traversal>
              <fragmentation>
                  <enable>no</enable>
              </fragmentation>
          </protocol-common>
          <peer-address>
              <ip>{{ peer_address }}</ip>
          </peer-address>
      </entry>

  - name: ipsec-tunnel
    xpath:  /config/devices/entry[@name='localhost.localdomain']/network
    element: |-
      <tunnel>
          <ipsec>
              <entry name="{{ tunnel_name }}">
                  <auto-key>
                      <ike-gateway>
                        <entry name="{{ ike_gateway_name }}"/>
                      </ike-gateway>
                  </auto-key>
                  <tunnel-monitor>
                      <enable>no</enable>
                    </tunnel-monitor>
                  <tunnel-interface>{{ tunnel_interface }}</tunnel-interface>
              </entry>
          </ipsec>
      </tunnel>


