# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: default_ike_crypto_profile
# label used for menu selection
label: default ike crypto profiles
description: This applies the default crypto profiles for devices that may be missing these elements

type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - IPSEC
    - Configure

variables:
  - name: emtpyvar
    description: placeholder
    default: emptyvar
    type_hint: hidden

snippets:
  - name: ike_crypto_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/network
    element: |-
      <ike>
         <crypto-profiles>
           <ike-crypto-profiles>
             <entry name="default">
               <encryption>
                 <member>aes-128-cbc</member>
                 <member>3des</member>
               </encryption>
               <hash>
                 <member>sha1</member>
               </hash>
               <dh-group>
                 <member>group2</member>
               </dh-group>
               <lifetime>
                 <hours>8</hours>
               </lifetime>
             </entry>
             <entry name="Suite-B-GCM-128">
               <encryption>
                 <member>aes-128-cbc</member>
               </encryption>
               <hash>
                 <member>sha256</member>
               </hash>
               <dh-group>
                 <member>group19</member>
               </dh-group>
               <lifetime>
                 <hours>8</hours>
               </lifetime>
             </entry>
             <entry name="Suite-B-GCM-256">
               <encryption>
                 <member>aes-256-cbc</member>
               </encryption>
               <hash>
                 <member>sha384</member>
               </hash>
               <dh-group>
                 <member>group20</member>
               </dh-group>
               <lifetime>
                 <hours>8</hours>
               </lifetime>
             </entry>
           </ike-crypto-profiles>
           <ipsec-crypto-profiles>
             <entry name="default">
               <esp>
                 <encryption>
                   <member>aes-128-cbc</member>
                   <member>3des</member>
                 </encryption>
                 <authentication>
                   <member>sha1</member>
                 </authentication>
               </esp>
               <dh-group>group2</dh-group>
               <lifetime>
                 <hours>1</hours>
               </lifetime>
             </entry>
             <entry name="Suite-B-GCM-128">
               <esp>
                 <encryption>
                   <member>aes-128-gcm</member>
                 </encryption>
                 <authentication>
                   <member>none</member>
                 </authentication>
               </esp>
               <dh-group>group19</dh-group>
               <lifetime>
                 <hours>1</hours>
               </lifetime>
             </entry>
             <entry name="Suite-B-GCM-256">
               <esp>
                 <encryption>
                   <member>aes-256-gcm</member>
                 </encryption>
                 <authentication>
                   <member>none</member>
                 </authentication>
               </esp>
               <dh-group>group20</dh-group>
               <lifetime>
                 <hours>1</hours>
               </lifetime>
             </entry>
           </ipsec-crypto-profiles>
           <global-protect-app-crypto-profiles>
             <entry name="default">
               <encryption>
                 <member>aes-128-cbc</member>
               </encryption>
               <authentication>
                 <member>sha1</member>
               </authentication>
             </entry>
           </global-protect-app-crypto-profiles>
         </crypto-profiles>
       </ike>

# ---------------------------------------------------------------------
# end of snippets section
